---
# tasks file for tfsec - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and setting up {{ tfsec_app }} {{ tfsec_version }}
  ansible.builtin.get_url:
    url: "{{ tfsec_dl_url }}"
    dest: "{{ tfsec_bin_path }}"
    owner: "{{ tfsec_file_owner }}"
    group: "{{ tfsec_file_group }}"
    mode: "{{ tfsec_file_mode }}"
