---
# tasks file for tfsec - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and setting up {{ tfsec_app }} {{ tfsec_version }}
  get_url:
    url: "{{ tfsec_dl_url }}"
    dest: "{{ tfsec_bin_path }}"
    mode: "{{ tfsec_bin_permission_mode }}"
